export const browserCoreExamples = [
  "openlocalbot browser status",
  "openlocalbot browser start",
  "openlocalbot browser stop",
  "openlocalbot browser tabs",
  "openlocalbot browser open https://example.com",
  "openlocalbot browser focus abcd1234",
  "openlocalbot browser close abcd1234",
  "openlocalbot browser screenshot",
  "openlocalbot browser screenshot --full-page",
  "openlocalbot browser screenshot --ref 12",
  "openlocalbot browser snapshot",
  "openlocalbot browser snapshot --format aria --limit 200",
  "openlocalbot browser snapshot --efficient",
  "openlocalbot browser snapshot --labels",
];

export const browserActionExamples = [
  "openlocalbot browser navigate https://example.com",
  "openlocalbot browser resize 1280 720",
  "openlocalbot browser click 12 --double",
  'openlocalbot browser type 23 "hello" --submit',
  "openlocalbot browser press Enter",
  "openlocalbot browser hover 44",
  "openlocalbot browser drag 10 11",
  "openlocalbot browser select 9 OptionA OptionB",
  "openlocalbot browser upload /tmp/file.pdf",
  'openlocalbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openlocalbot browser dialog --accept",
  'openlocalbot browser wait --text "Done"',
  "openlocalbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openlocalbot browser console --level error",
  "openlocalbot browser pdf",
];
